#!/bin/bash

echo Running apt update
apt update
echo Running apt upgrade -y
apt upgrade -y

echo Installing python and pip
apt install python3 -y
apt install python3-pip -y

echo installing yaml support
python -m pip install yaml
